# ruff: noqa: E501
# Generated by Django 5.2.16 on 2026-07-18 07:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agreements", "0003_funding_lifecycle_fields"),
        ("integrations", "0001_initial"),
        ("organizations", "0002_organization_risk_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("secret_ciphertext", models.BinaryField()),
                ("secret_nonce", models.BinaryField()),
                ("secret_encrypted_data_key", models.BinaryField()),
                ("secret_kms_key_id", models.CharField(max_length=512)),
                ("previous_secret_ciphertext", models.BinaryField(blank=True, null=True)),
                ("previous_secret_nonce", models.BinaryField(blank=True, null=True)),
                ("previous_secret_encrypted_data_key", models.BinaryField(blank=True, null=True)),
                (
                    "previous_secret_kms_key_id",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("previous_secret_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_endpoints",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=128)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("sequence", models.PositiveBigIntegerField()),
                ("correlation_id", models.CharField(max_length=128)),
                ("causation_id", models.CharField(blank=True, max_length=128, null=True)),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_events",
                        to="agreements.escrowagreement",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RETRYING", "Retrying"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("first_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="integrations.webhookendpoint",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="integrations.webhookevent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="webhookendpoint",
            constraint=models.UniqueConstraint(
                fields=("organization", "url"),
                name="integrations_webhook_endpoint_organization_url_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["organization", "occurred_at"], name="integ_webhook_evt_org_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                fields=("agreement", "event_type", "sequence"),
                name="integrations_webhook_event_agreement_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="integrations_webhook_event_version_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="integ_webhook_del_due_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("endpoint", "event"),
                name="integrations_webhook_delivery_endpoint_event_unique",
            ),
        ),
    ]
