# Generated by Django 5.2.16 on 2026-07-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_webhookendpoint_webhookevent_webhookdelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='replay_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='delivery_command_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
