# Generated by Django 5.2.16 on 2026-07-22 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_disputerecommendation'),
        ('risk', '0003_fundingriskreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeRiskPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=64, unique=True)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisputeRiskReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_version', models.CharField(max_length=64)),
                ('policy_configuration', models.JSONField(default=dict)),
                ('inputs', models.JSONField(default=dict)),
                ('summary', models.TextField()),
                ('timeline', models.JSONField(default=list)),
                ('customer_history', models.JSONField(default=dict)),
                ('organization_history', models.JSONField(default=dict)),
                ('evidence_integrity', models.JSONField(default=dict)),
                ('score', models.PositiveSmallIntegerField()),
                ('flags', models.JSONField(default=list)),
                ('suspicion_result', models.CharField(choices=[('NO_SUSPICION', 'No suspicion'), ('SUSPICIOUS_INDICATORS', 'Suspicious indicators')], default='NO_SUSPICION', max_length=32)),
                ('generated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='risk_report', to='disputes.dispute')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='risk.disputeriskpolicy')),
            ],
            options={
                'ordering': ['generated_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='risk_dispute_score_between_0_and_100'), models.CheckConstraint(condition=models.Q(('suspicion_result__in', ['NO_SUSPICION', 'SUSPICIOUS_INDICATORS'])), name='risk_dispute_suspicion_result_is_known')],
            },
        ),
    ]
