# Generated by Django 5.2.16 on 2026-07-20 18:21

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def seed_simulated_rates(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Seed fixed simulated display rates; they never feed the ledger."""
    del schema_editor
    exchange_rate = apps.get_model("organizations", "ExchangeRate")
    recorded_at = datetime(2026, 1, 1, tzinfo=UTC)
    exchange_rate.objects.get_or_create(
        base_currency="BRL",
        quote_currency="USD",
        defaults={
            "rate_micros": 180_000,
            "is_simulated": True,
            "recorded_at": recorded_at,
        },
    )
    exchange_rate.objects.get_or_create(
        base_currency="USD",
        quote_currency="BRL",
        defaults={
            "rate_micros": 5_400_000,
            "is_simulated": True,
            "recorded_at": recorded_at,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organization_risk_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        choices=[("BRL", "Brazilian real"), ("USD", "United States dollar")],
                        max_length=3,
                    ),
                ),
                (
                    "quote_currency",
                    models.CharField(
                        choices=[("BRL", "Brazilian real"), ("USD", "United States dollar")],
                        max_length=3,
                    ),
                ),
                ("rate_micros", models.PositiveBigIntegerField()),
                ("is_simulated", models.BooleanField(default=True)),
                ("recorded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-recorded_at", "-created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("base_currency", models.F("quote_currency")), _negated=True
                        ),
                        name="organizations_exchange_rate_distinct_currencies",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_simulated_rates, migrations.RunPython.noop),
    ]
