# ruff: noqa: E501
# Generated by Django 5.2.16 on 2026-07-18 13:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0003_funding_lifecycle_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REPORT_GENERATING', 'Report generating'), ('ANALYST_REVIEW', 'Analyst review'), ('ADMIN_REVIEW', 'Admin review'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=32)),
                ('opened_at', models.DateTimeField()),
                ('sla_due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='agreements.escrowagreement')),
            ],
            options={
                'ordering': ['opened_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('extension', models.CharField(max_length=8)),
                ('media_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='disputes.dispute')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_access_grants', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='disputes.evidence')),
            ],
            options={
                'ordering': ['issued_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'opened_at'], name='disputes_di_status_3cbd82_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'REPORT_GENERATING', 'ANALYST_REVIEW', 'ADMIN_REVIEW', 'RESOLVED'])), name='disputes_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.CheckConstraint(condition=models.Q(('sla_due_at__gt', models.F('opened_at'))), name='disputes_sla_after_opening'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['sha256'], name='disputes_ev_sha256_3e67ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='disputes_evidence_size_positive'),
        ),
        migrations.AddIndex(
            model_name='evidenceaccessgrant',
            index=models.Index(fields=['evidence', 'expires_at'], name='disputes_ev_evidenc_0de90b_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenceaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('issued_at'))), name='disputes_evidence_grant_expires_after_issue'),
        ),
    ]
