# Generated by Django 5.2.16 on 2026-07-22 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.CharField(max_length=128, unique=True)),
                ('recommendation', models.CharField(choices=[('RELEASE_TO_ORGANIZATION', 'Release to organization'), ('REFUND_TO_CUSTOMER', 'Refund to customer')], max_length=32)),
                ('rationale', models.TextField(max_length=1000)),
                ('recommended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_recommendations', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='analyst_recommendation', to='disputes.dispute')),
            ],
            options={
                'ordering': ['recommended_at', 'id'],
            },
        ),
    ]
