# Generated by Django 5.2.16 on 2026-07-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_disputerecommendation'),
        ('risk', '0004_disputeriskpolicy_disputeriskreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputerecommendation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='risk.disputeriskreport'),
        ),
        migrations.AddConstraint(
            model_name='disputerecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('recommendation__in', ['RELEASE_TO_ORGANIZATION', 'REFUND_TO_CUSTOMER'])), name='disputes_recommendation_choice_is_known'),
        ),
        migrations.AddConstraint(
            model_name='disputerecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('command_id', ''), _negated=True), name='disputes_recommendation_command_id_not_empty'),
        ),
    ]
