# Generated by Django 5.2.16 on 2026-07-22 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_disputerecommendation_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeAdminDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.CharField(max_length=128, unique=True)),
                ('decision', models.CharField(choices=[('RELEASE_TO_ORGANIZATION', 'Release to organization'), ('REFUND_TO_CUSTOMER', 'Refund to customer')], max_length=32)),
                ('rationale', models.TextField(max_length=1000)),
                ('decided_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_admin_decisions', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admin_decision', to='disputes.dispute')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_decisions', to='disputes.disputerecommendation')),
            ],
            options={
                'ordering': ['decided_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('decision__in', ['RELEASE_TO_ORGANIZATION', 'REFUND_TO_CUSTOMER'])), name='disputes_admin_decision_choice_is_known'), models.CheckConstraint(condition=models.Q(('command_id', ''), _negated=True), name='disputes_admin_decision_command_id_not_empty')],
            },
        ),
    ]
