# Generated by Django 5.2.16 on 2026-07-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_customer_otp_challenge'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerotpchallenge',
            new_name='delivery_cu_agreeme_1c0725_idx',
            old_name='delivery_cu_agreeme_280d24_idx',
        ),
    ]
