# Generated by Django 5.2.16 on 2026-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rename_delivery_cu_agreeme_280d24_idx_delivery_cu_agreeme_1c0725_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerotpchallenge',
            name='purpose',
            field=models.CharField(
                choices=[('DELIVERY_ACCEPTANCE', 'Delivery acceptance'), ('DISPUTE', 'Dispute')],
                default='DELIVERY_ACCEPTANCE',
                max_length=32,
            ),
        ),
    ]
